Compensation metric
DeltaRCM/DeltaMetrics pull request #137
Opened 2023-02-10 16:10 UTC by amoodie

adds a function to compute compensation.

todo
 - [ ] rework how `strata` is pulled for a `Section`. `sect.strata` should return a 2d DataArray with strata for that section.
 - [ ] clarify and streamline `Cube.strata`, and how `Section` gets this information.
 - [ ] documentation example for how to use do the computation and briefly what to do with the outputs. E.g., how to do a bin average, how to fit a line to the bin averages, what the rollover point means. Use the equations.
 - [ ] tests (1d, 2d, 3d, simple, golf)

2026-01-27 23:46 UTC, amoodie commented
@ericbarefoot I think this is ready for your review now. I would appreciate some review of the description and calculation of the compensation values. There is an example that shows how it works.

I still need to add tests.

2026-01-30 14:17 UTC, amoodie commented
Now has tests for the compensation function API, but actual calculation results. I'm not sure how to make a simple dataset to test.

2026-03-12 06:04 UTC, ericbarefoot requested changes
Mostly a few small changes that should be made. Core function is fine. Happy to make it a priority to put a test dataset on zenodo that `pooch` can fetch for actual compensation stats. Could coarsen it for ease of use.

2026-03-12 06:04 UTC, ericbarefoot commented on docs/source/guides/examples/computations/stratigraphy_temporal_subset.rst
This one is very cool.

2026-03-12 06:04 UTC, ericbarefoot commented on sandplover/section.py
> +            raise utils.NoStratigraphyError(obj=self, var="strata")
This needs to be just a `NoStratigraphyError()` call since you import from `utils` at the top of the script.

2026-03-12 06:04 UTC, ericbarefoot commented on sandplover/section.py
> +        See :obj:`~deltametrics.cube.DataCube.strata` for more information.
I think you mean `sandplover.cube.StratigraphyCube.strata`

2026-03-12 06:04 UTC, ericbarefoot commented on sandplover/section.py
> +                name=var,
I think this `var` has no reference. What's it's scope? I thin you are looking to pass the variable, but I don't know the best way to do that right now.

2026-03-12 06:04 UTC, ericbarefoot commented on sandplover/section.py
Not sure if I am quite understanding this property of section, and how the call works. It seems to function, but looks like there's a few bugs.

2026-03-12 06:04 UTC, ericbarefoot commented on sandplover/cube.py
> +            Conversely, when a time-series is provided, the each value is
typo: 

> Conversely, when a time-series is provided, ~the~ each value is

2026-03-12 06:04 UTC, ericbarefoot commented on sandplover/cube.py
Can you clarify what the special value of this is? I am struggling to see where this gets used, and why subsidence is not just one of many auxiliary variables (or a spatially-explicit variable?). Why does it show up here? I think I'm just not understanding.

2026-03-12 06:04 UTC, ericbarefoot commented on sandplover/strat.py
> +        #   and the intervals are not equally spaced?
great question. no idea

2026-03-12 06:04 UTC, ericbarefoot commented on sandplover/strat.py
> +        #   and the intervals are not equally spaced?
lemme think about it

2026-03-12 06:04 UTC, ericbarefoot commented on sandplover/strat.py
> +        #  array of all ones. How to compute over 3d?
3D is a reasonable extension of the 2D routine. 1D doesn't make a lot of sense, but we could consider it. would need multiple samples in 1D tho. is not defined for a single "core"

2026-03-12 06:04 UTC, ericbarefoot commented on sandplover/strat.py
> +    # run the computation routine (jitted?)
Do you want to enforce/require `numba`? That might not be a bad idea.

2026-03-12 06:04 UTC, ericbarefoot commented on sandplover/strat.py
Implementation looks fine to me.

2026-03-12 06:04 UTC, ericbarefoot commented on tests/strat_test.py
This definitely tests the error functions. Should we also have a test for making sure the function does what it says? Like a predetermined outcome on the golf dataset or something?

2026-03-20 15:18 UTC, amoodie commented on sandplover/cube.py
Subsidence can be just a regular value, but we need to know which of your many variables *is* subsidence if you want us to apply it during the calculation of preserved sediments. By default we assume zero. It could be spatially-explicit, but we don't currently support that (aka I didn't implement that yet).

2026-03-20 16:04 UTC, elbeejay commented on sandplover/strat.py
> +        #   and the intervals are not equally spaced?
One idea would be to resample yourself to the smallest time interval present in the data. Say you had time intervals of 1 year, 2 years, 5 years, with corresponding three indices, 0, 1, 2, you could resample to a bigger volume with equal spacings of 1 year (8 indices), and then I'd imagine your existing methods would work. Let's you maintain the highest temporal fidelity you have, with the assumption that you can somehow resample or subdivide the longer stretches of time into that smallest common interval (and at a higher computational cost).

2026-04-22 14:31 UTC, amoodie commented on sandplover/section.py
> +                name=var,
thanks for noticing all the issues here. I think was something I never fully finished implementing. Now it has a better explanation and an example of what you can use this attribute for.

2026-04-22 14:47 UTC, amoodie commented on sandplover/strat.py
> +        #   and the intervals are not equally spaced?
opened issue #237, not addressing this in this PR

2026-04-22 14:50 UTC, amoodie commented on sandplover/strat.py
> +    # run the computation routine (jitted?)
sandplover already requires numba. I didn't end up using it for this function at present, but it could be changed in the future if this is a computation bottleneck

2026-04-22 14:52 UTC, amoodie commented on tests/strat_test.py
I've tried to avoid predetermined calculations, as they seem difficult to maintain and understand (originally did this with some of the shoreline roughness calculations, for example). 

If there was a simple synthetic case we could use, where the answer is known, that would work. Like a random normal distribution of elevation changes plus background aggradation should equal compensation of xxxxx. 

I don't know enough to be able to implement this tho

2026-04-22 14:55 UTC, amoodie commented on tests/strat_test.py
I opened an issue to track this testing as well #238

2026-04-22 19:30 UTC, merged

2026-04-22 19:31 UTC, amoodie commented
Thanks for the helpful review @ericbarefoot !