Add Morphological Planform
DeltaRCM/DeltaMetrics pull request #63
Opened 2021-07-09 19:08 UTC by elbeejay

Work in progress, but the goal is to do the following:

1. Add an alternative `MorphologicalPlanform` based on a mathematical morphology method similar to the one described in [Geleynse et al 2012](https://doi.org/10.1029/2012GL052845)
2. Make the masking classes and methods more flexible to handle both the new "MPM" (morphological planform method) and existing "OAM" methodologies -- with the default behavior falling back on the OAM

Currently an initial version of the new class is in place, and the masking operations (and related unit tests) have been modified to allow the existing unit tests to pass, ensuring that the pre-existing OAM functionality has not been altered.

Of note, the `angle_threshold` has been generalized to a `contour_threshold` as this is more generic. For the OAM we use an angle threshold, but for the new MPM, this threshold is a value between 0 and 1. 

---

To do:

- [ ] write unit tests and make sure new method works
- [ ] fix doc-strings
- [ ] improve error messages
- [ ] add examples and documentation
- [ ] see if code can be made more elegant / better "flexibility"

2021-09-22 21:44 UTC, amoodie requested changes
Hi @elbeejay, I didn't really dig into all the refactoring, but I looked at the implementation of the new planform, and I think I understand the way this cascades into changes in masking.

I think it makes sense, and if you are happy with it, I'm good for you to go ahead with it. 

BUT. This seems like a pretty big breaking change for masking. So, I suggest we either increment the minor version number (so go `0.3.0`), or try to make the transition here smoother and then go with a smaller patch designation (so go `0.2.1`).  If you want to go the latter route, I think the mininum would be to make it so that the old mask tests could pass without the changes. This would mean implementing `dummy properties like `angle_threshold` to pass on to the new props and raise a deprecation warning. You probably have a better sense than I do for how much work that would be. To be clear, I'm fine with just going ahead with a 0.3.

Either way, the version number def needs to be changed.

2021-09-24 01:59 UTC, elbeejay commented
Sorry I didn't have it in me to dig through the PR and establish deprecation pathways. Will keep that in mind in the future as it is would be a better practice when making breaking changes. 

Just pushed a commit to jump the version to 0.3.0

2021-09-24 13:22 UTC, amoodie commented
Understood. I think it is important to try at least to some extent to keep things backwards compatible, now that we are starting to publish on work using DeltaMetrics. For example, I need to pin my faulting-subsidence stuff to version 0.2 now, or it would not work.

Go ahead and merge if you're ready.

2021-09-24 13:25 UTC, elbeejay commented
> Understood. I think it is important to try at least to some extent to keep things backwards compatible, now that we are starting to publish on work using DeltaMetrics. For example, I need to pin my faulting-subsidence stuff to version 0.2 now, or it would not work.
> 
> Go ahead and merge if you're ready.

Shouldn't be horrible to make backward-compatible if you think it is worth doing. Let me know and I can add the deprecation hooks

2021-09-24 20:07 UTC, merged